// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/goods/good.proto

package good

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Good struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ScanCode             string   `protobuf:"bytes,3,opt,name=scan_code,json=scanCode,proto3" json:"scan_code,omitempty"`
	Price                string   `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Standard             string   `protobuf:"bytes,5,opt,name=standard,proto3" json:"standard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Good) Reset()         { *m = Good{} }
func (m *Good) String() string { return proto.CompactTextString(m) }
func (*Good) ProtoMessage()    {}
func (*Good) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f0c6740ea846d8, []int{0}
}

func (m *Good) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Good.Unmarshal(m, b)
}
func (m *Good) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Good.Marshal(b, m, deterministic)
}
func (m *Good) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Good.Merge(m, src)
}
func (m *Good) XXX_Size() int {
	return xxx_messageInfo_Good.Size(m)
}
func (m *Good) XXX_DiscardUnknown() {
	xxx_messageInfo_Good.DiscardUnknown(m)
}

var xxx_messageInfo_Good proto.InternalMessageInfo

func (m *Good) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Good) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Good) GetScanCode() string {
	if m != nil {
		return m.ScanCode
	}
	return ""
}

func (m *Good) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Good) GetStandard() string {
	if m != nil {
		return m.Standard
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f0c6740ea846d8, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	Good                 *Good    `protobuf:"bytes,1,opt,name=good,proto3" json:"good,omitempty"`
	Goods                []*Good  `protobuf:"bytes,2,rep,name=goods,proto3" json:"goods,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f0c6740ea846d8, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetGood() *Good {
	if m != nil {
		return m.Good
	}
	return nil
}

func (m *Response) GetGoods() []*Good {
	if m != nil {
		return m.Goods
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f0c6740ea846d8, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Good)(nil), "good.Good")
	proto.RegisterType((*Request)(nil), "good.Request")
	proto.RegisterType((*Response)(nil), "good.Response")
	proto.RegisterType((*Error)(nil), "good.Error")
}

func init() { proto.RegisterFile("proto/goods/good.proto", fileDescriptor_a5f0c6740ea846d8) }

var fileDescriptor_a5f0c6740ea846d8 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xdd, 0xb6, 0x59, 0xdb, 0x29, 0xec, 0x61, 0x10, 0x09, 0x2b, 0x48, 0xa9, 0x17, 0x0f,
	0xb2, 0xc2, 0x7a, 0xf6, 0x24, 0xd2, 0x7b, 0xfe, 0x80, 0xd4, 0x66, 0x90, 0x1e, 0xcc, 0x74, 0x93,
	0x78, 0xf0, 0xdf, 0x4b, 0xa6, 0x11, 0x96, 0xbd, 0x94, 0x97, 0xef, 0x4d, 0x99, 0xf7, 0x06, 0x6e,
	0x17, 0xcf, 0x91, 0x9f, 0xbf, 0x98, 0x6d, 0x90, 0xef, 0x41, 0x00, 0x56, 0x49, 0xf7, 0xbf, 0x50,
	0x0d, 0xcc, 0x16, 0x77, 0x50, 0xcc, 0x56, 0x6f, 0xba, 0xcd, 0x63, 0x63, 0x8a, 0xd9, 0x22, 0x42,
	0xe5, 0xc6, 0x6f, 0xd2, 0x85, 0x10, 0xd1, 0x78, 0x07, 0x4d, 0x98, 0x46, 0xf7, 0x31, 0xb1, 0x25,
	0x5d, 0x8a, 0x51, 0x27, 0xf0, 0xc6, 0x96, 0xf0, 0x06, 0xd4, 0xe2, 0xe7, 0x89, 0x74, 0x25, 0xc6,
	0xfa, 0xc0, 0x3d, 0xd4, 0x21, 0x8e, 0xce, 0x8e, 0xde, 0x6a, 0x95, 0xff, 0xc8, 0xef, 0xbe, 0x81,
	0x6b, 0x43, 0xa7, 0x1f, 0x0a, 0xb1, 0x3f, 0x41, 0x6d, 0x28, 0x2c, 0xec, 0x02, 0xe1, 0x3d, 0x48,
	0x32, 0xc9, 0xd2, 0x1e, 0xe1, 0x20, 0x91, 0x53, 0x46, 0x23, 0x1c, 0x3b, 0x50, 0xd2, 0x45, 0x17,
	0x5d, 0x79, 0x31, 0xb0, 0x1a, 0xf8, 0x00, 0x5b, 0xf2, 0x9e, 0x7d, 0xd0, 0xa5, 0x8c, 0xb4, 0xeb,
	0xc8, 0x7b, 0x62, 0x26, 0x5b, 0xfd, 0x2b, 0x28, 0x01, 0xa9, 0xa9, 0x14, 0x4a, 0xfb, 0x94, 0x11,
	0x8d, 0x1d, 0xb4, 0x96, 0xc2, 0xe4, 0xe7, 0x25, 0xce, 0xec, 0xf2, 0x11, 0xce, 0xd1, 0xf1, 0x09,
	0xd4, 0x90, 0x97, 0x95, 0x03, 0x45, 0x3c, 0x8b, 0xb1, 0xdf, 0xad, 0xfa, 0xbf, 0x51, 0x7f, 0xf5,
	0xb9, 0x95, 0x93, 0xbf, 0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0x51, 0x92, 0xa1, 0x87, 0x8c, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Goods service

type GoodsClient interface {
	// 获取商品信息
	Get(ctx context.Context, in *Good, opts ...client.CallOption) (*Response, error)
}

type goodsClient struct {
	c           client.Client
	serviceName string
}

func NewGoodsClient(serviceName string, c client.Client) GoodsClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "good"
	}
	return &goodsClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *goodsClient) Get(ctx context.Context, in *Good, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Goods.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Goods service

type GoodsHandler interface {
	// 获取商品信息
	Get(context.Context, *Good, *Response) error
}

func RegisterGoodsHandler(s server.Server, hdlr GoodsHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Goods{hdlr}, opts...))
}

type Goods struct {
	GoodsHandler
}

func (h *Goods) Get(ctx context.Context, in *Good, out *Response) error {
	return h.GoodsHandler.Get(ctx, in, out)
}
